name: Weekly US Drug List Update

on:
  schedule:
    - cron: '0 1 * * 0' # Every Sunday at 01:00 UTC
  workflow_dispatch:   # ✅ This enables the "Run workflow" button


jobs:
  update-us-drugs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

- name: Run US drug extraction script
  run: node scripts/extract-us-drugs.js
  working-directory: ${{ github.workspace }}

      - name: Commit updated us-drugs.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/data/us-drugs.json

          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
          else
            git commit -m "🔄 Weekly US drug list update"
            git push
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
